config/routes.rb
Rails.application.routes.draw do

    root to: "public/homes#top"  
    get "/about" => "public/homes#about", as:"about"
    
    # customer
    devise_for :customers, skip: [:passwords],  controllers: {
      registrations: "public/registrations",
      sessions: "public/sessions"
    }
    
    scope module: :public do
    # namespace :public do
      resource :customers, only: [:show]
      get "/customers/information/edit" => "customers#edit"
      patch "/customers/information" => "customers#update"
      get "/customers/comfirm" => "customers#comfirm"
      patch "/customers/withdrawal" => "customers#withdrawal"
      
      resources :items, only: [:index, :show]
      resources :cart_items, only: [:index, :create, :update, :destroy]
      delete "/cart_items/" => "cart_items#destroy_all"
      
      post "/orders/comfirm" => "orders#comfirm"
      get "/orders/thanks" => "orders#thanks", as:"thanks" #名前をつけることで詳細にリンクするバグを回避
      resources :orders, only: [:index, :new, :create, :show]
      
      resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    end
    
    # admin
    devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
      sessions: "admin/sessions"
    }
    
    namespace :admin do
      resources :genres, only: [:index, :create, :edit, :update]
      resources :items
      resources :customers, only: [:index, :show, :edit, :update] do
      resources :orders, only: [:index]
      end
      resources :orders, only: [:index, :show, :update]
      resources :order_detail, only: [:update]
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details
  
  has_one_attached :item_image

  def add_tax_price
        (self.price * 1.10).round
  end

  def get_item_image(width,height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      item_image.attache(io:File.open(file_path),
      filename: 'default-image.jpg', content_type:'image/jpg')
    end
      item_image.variant(resize_to_limit:[width,height]).processed
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_path
  end

  def show
    @item = Item.find(params[:id]) 
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, :genre_id, :introduction, :price, :is_active, :item_image)
  end
  
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <h4 class="m-5 d-inline-block px-3" style="background-color:#eeeeee">商品編集</h4>
  
  <div class="row justify-content-center">

      <%= form_with model: [:admin, @item] do |f| %>
        <table class="item_new_table">
          <tbody>
            <tr class="mb-3">
              <td><%= f.label :商品画像 %></td>
              <td><%= f.file_field :item_image, accept: "image/" %></td>
            </tr>
            <tr>
              <td><%= f.label :商品名 %></td>
              <td><%= f.text_field :name, class: 'form-control', placeholder:"商品名" %></td>
            </tr>
            <tr>
              <td><%= f.label :商品説明 %></td>
              <td><%= f.text_area :introduction, rows: "5%", class: 'form-control', placeholder:"ここに説明文を記述します" %></td>
            </tr>
            <tr>
              <td><%= f.label :ジャンル %></td>
              <td><%= f.collection_select :genre_id, Genre.all, :id, :name,  { include_blank: '-- 選択してください --'} %></td>
            </tr>
            <tr>
              <td><%= f.label :税抜価格 %></td>
              <td><%= f.text_field :price, class: 'form-control', placeholder:"1000" %></td>
              <td> 円</td>
            </tr>
            <tr>
              <td><%= f.label :販売ステータス %></td>
              <td>
                <%= f.radio_button :is_active, true %>
                <%= f.label :is_active, "販売中" %>　　
                <%= f.radio_button :is_active, false %>
                <%= f.label :is_active, "販売停止中" %>
              </td>
            </tr>
          </tbody>
        </table>
        <div align="center">
          <%= f.submit "変更を更新", class: 'btn btn-success my-5 py-2 px-5' %>
        </div>
      <% end %>
    
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row m-5 justify-content-center">
    <div class="col-2">
      <h4 style="background-color:#eeeeee" align="center">商品一覧</h4>
    </div>
    <div class="col-7" align="right">
      <%= link_to "＋", new_admin_item_path, class:"item_new btn btn-light" %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
      <table class="table">
        <thead class="thead-light">
          <th width="10%">商品ID</th>
          <th width="30%">商品名</th>
          <th width="10%">税抜価格</th>
          <th width="30%">ジャンル</th>
          <th width="20%">ステータス</th>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td>
                <%= link_to  admin_item_path(item.id), class:"link-dark" do %>
                  <%= item.name %></td>
                <% end%>
              <td><%= item.price %></td>
              <td><%= item.genre.name %></td>
              <td>
                <% if item.is_active? %> 
                  <p class="font-weight-bold", style="color:#32cd32">販売中</p>
                <% else %>
                  <p class="font-weight-bold", style="color:#d3d3d3">販売停止中</p>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-lg-2"></div>
  </div>
       <%= paginate @items, class:"pagination"%>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <h4 class="m-5 d-inline-block px-3" style="background-color:#eeeeee">商品新規登録</h4>
  
  <div class="row justify-content-center">

      <%= form_with model: @item, url: admin_items_path, local: true do |f| %>
        <table class="item_new_table">
          <tbody>
            <tr class="mb-3">
              <td><%= f.label :商品画像 %></td>
              <td><%= f.file_field :item_image, accept: "image/" %></td>
            </tr>
            <tr>
              <td><%= f.label :商品名 %></td>
              <td><%= f.text_field :name, class: 'form-control', placeholder:"商品名" %></td>
            </tr>
            <tr>
              <td><%= f.label :商品説明 %></td>
              <td><%= f.text_area :introduction, rows: "5%", class: 'form-control', placeholder:"ここに説明文を記述します" %></td>
            </tr>
            <tr>
              <td><%= f.label :ジャンル %></td>
              <td><%= f.collection_select :genre_id, Genre.all, :id, :name,  { include_blank: '-- 選択してください --'} %></td>
            </tr>
            <tr>
              <td><%= f.label :税抜価格 %></td>
              <td><%= f.text_field :price, class: 'form-control', placeholder:"1000" %></td>
              <td> 円</td>
            </tr>
            <tr>
              <td><%= f.label :販売ステータス %></td>
              <td>
                <%= f.radio_button :is_active, true %>
                <%= f.label :is_active, "販売中" %>　　
                <%= f.radio_button :is_active, false %>
                <%= f.label :is_active, "販売停止中" %>
              </td>
            </tr>
          </tbody>
        </table>
        <div align="center">
          <%= f.submit "新規登録", class: 'btn btn-success py-2 px-5 mb-5' %>
        </div>
      <% end %>
    
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <h4 class="m-5 d-inline-block px-3" style="background-color:#eeeeee">商品詳細</h4>
  
  <div class="row justify-content-center">
    <div class="pr-5" align="left">
      <%= image_tag @item.get_item_image(100,60) %>
    </div>
  
    <table width="30%">
      <tbody>
        <tr>
            <td>商品名</td>
            <td><%= @item.name %></td>
        </tr>
        <tr>
          <td>商品説明</td>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <td>ジャンル</td>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <td>税込価格<br>(税抜価格)</td>
          <td>
            <%= @item.add_tax_price.to_s(:delimited) %>
            (<%= @item.price.to_s(:delimited) %>) 円
          </td>
        </tr>
        <tr>
          <td>販売ステータス</td>
          <td>
            <% if @item.is_active? %> 
              <p class="font-weight-bold" style="color:#32cd32">販売中</p>
            <% else %>
              <p class="font-weight-bold" style="color:#d3d3d3">販売停止中</p>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div align="center">
    <%= link_to "編集する", edit_admin_item_path, class:"btn btn-success my-5 py-2 px-5" %>
  </div>
</div>