config/routes.rb
Rails.application.routes.draw do

    root to: "public/homes#top"  
    get "/about" => "public/homes#about", as:"about"
    
    # customer
    devise_for :customers, skip: [:passwords],  controllers: {
      registrations: "public/registrations",
      sessions: "public/sessions"
    }
    
    scope module: :public do
    # namespace :public do
      resource :customers, only: [:show]
      get "/customers/information/edit" => "customers#edit"
      patch "/customers/information" => "customers#update"
      get "/customers/comfirm" => "customers#comfirm"
      patch "/customers/withdrawal" => "customers#withdrawal"
      
      resources :items, only: [:index, :show]
      resources :cart_items, only: [:index, :create, :update, :destroy]
      delete "/cart_items/" => "cart_items#destroy_all"
      
      post "/orders/comfirm" => "orders#comfirm"
      get "/orders/thanks" => "orders#thanks", as:"thanks" #名前をつけることで詳細にリンクするバグを回避
      resources :orders, only: [:index, :new, :create, :show]
      
      resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    end
    
    # admin
    devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
      sessions: "admin/sessions"
    }
    
    namespace :admin do
      resources :genres, only: [:index, :create, :edit, :update]
      resources :items
      resources :customers, only: [:index, :show, :edit, :update] do
      resources :orders, only: [:index]
      end
      resources :orders, only: [:index, :show, :update]
      resources :order_detail, only: [:update]
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :Admin
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  validates :first_name, presence:true
  validates :last_name, presence:true
  validates :first_name_kana, presence:true
  validates :last_name_kana, presence:true
  validates :post_code, presence:true
  validates :address, presence:true
  validates :telephone_number, presence:true
  
  # 会員フルネーム
  def full_name
    self.last_name + " " + self.first_name
  end
  
  # 会員カナフルネーム
  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end
  
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
    else
      render edit
    end
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :post_code, :address, :telephone_number, :email, :is_active, :is_deleted)  
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <h4 class="d-inline-block px-3 my-5" style="background-color:#eeeeee">
    <%= @customer.full_name %>さんの会員情報編集
  </h4>
  
  <div class="row">
    <div class="col-1"></div>
    <div class="col-8">
      <table class="table table-borderless">
        <%= form_with model: [:admin,@customer] do |f| %>
          <thead>
            <th width="25%"></th>
            <th width="25%"></th>
            <th width="25%"></th>
            <th width="25%"></th>
          </thead>
          <tbody>
              <tr>
              <td>会員ID</td>
              <td>
                <%= @customer.id %>
              </td>
            </tr>
            
            <tr>
              <td>名前</td>
              <td>
                <%= f.text_field :last_name, class: 'form-control', placeholder:"令和" %>
              </td>
              <td>
                <%= f.text_field :first_name, class: 'form-control', placeholder:"道子" %>
              </td>
            </tr>
      
            <tr>
              <td>フリガナ</td>
              <td>
                  <%= f.text_field :last_name_kana, class: 'form-control', placeholder:"レイワ" %>
              </td>
              <td>
                  <%= f.text_field :first_name_kana, class: 'form-control', placeholder:"ミチコ" %>
              </td>
            </tr>
    
            <tr>
              <td><%= f.label :"郵便番号"%></td>
              <td>
                <%= f.text_field :post_code, class: 'form-control', placeholder:"0000000" %>
              </td>
            </tr>
            
              <tr>
              <td><%= f.label :"住所"%></td>
              <td colspan="3">
                <%= f.text_field :address, class: 'form-control', placeholder:"東京都渋谷区佐々木神園町0-0" %>
              </td>
              <td></td>
            </tr>
            
            <tr>
              <td><%= f.label :"電話番号"%></td>
              <td>
                <%= f.text_field :telephone_number, class: 'form-control', placeholder:"00000000000" %>
              </td>
            </tr>
    
            <tr>
              <td><%= f.label :メールアドレス %></td>
              <td>
                <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control', placeholder:"sample@sample.com" %>
              </td>
            </tr>
            
            <tr>
              <td>会員ステータス</td>
              <td>
                <%= f.radio_button :is_deleted, false %>
                <%= f.label :is_deleted, "有効" %>　　
                <%= f.radio_button :is_deleted, true %>
                <%= f.label :is_deleted, "退会" %>
              </td>
            </tr>
    
            <tr>
              <td></td>
              <td>
                <%= f.submit "変更を保存", class: 'btn btn-success py-3 px-5' %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <h4 class="m-5 d-inline-block px-3" style="background-color:#eeeeee">会員一覧</h4>

  <div class="row">
    <div class="col-2"></div>
    <div class="col-8">
      <table class="table">
        <thead class="thead-light">
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td>
            <%= link_to admin_customer_path(customer.id) do %>
              <%= customer.full_name %>
            <% end %>
            </td>
            <td><%= customer.email %></td>
            <td>
              <% if customer.is_deleted? %> 
                <p class="font-weight-bold", style="color:#d3dd3d3">退会</p>
              <% else %>
                <p class="font-weight-bold", style="color:#32cd32">有効</p>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-2"></div>
  </div>
  <%= paginate @customers, class:"pagination"%>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <h4 class="my-5 d-inline-block px-4" style="background-color:#eeeeee">
    <%= @customer.full_name %>さんの会員詳細
  </h4>
  <div class="row ml-5">
  <table class="table table-borderless">
    <thead>
      <th width="15%"></th>
      <th width="85%"></th>
    </thead>
    <tbody>
      <tr>
        <td>会員ID</td>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <td>氏名</td>
        <td><%= @customer.last_name %>　<%= @customer.first_name %></td>
      </tr>
      <tr>
        <td>フリガナ</td>
        <td><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
      </tr>
      <tr>
        <td>郵便番号</td>
        <td><%= @customer.post_code %></td>
      </tr>
      <tr>
        <td>住所</td>
        <td><%= @customer.address %></td>
      </tr>
      <tr>
        <td>電話番号</td>
        <td><%= @customer.telephone_number %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td><%= @customer.email %></td>
      </tr>
      <tr>
        <td>会員ステータス</td>
        <td>
          <% if @customer.is_deleted? %>  
              <p class="font-weight-bold" style="color:#d3dd3d3">退会</p>
            <% else %>
              <p class="font-weight-bold" style="color:#32cd32">有効</p>
            <% end %>
        </td>
      </tr>
      <tr>
        <td></td>
        <td></td>
      </tr>
    </tbody>
  </table>
  </div>
  <div class="row mb-5">
    <div class="col-2"></div>
    <div class="col-2">
      <%= link_to "編集する", edit_admin_customer_path, class:"btn btn-success py-2 px-3 ml-5" %>
    </div>
    <div class="col-3">
      <%= link_to "注文履歴一覧を見る", admin_orders_path, class:"btn btn-primary py-2 px-3" %>  
    </div>
    <div class="col-5"></div>
  </div>
</div>