config/routes.rb
Rails.application.routes.draw do

    root to: "public/homes#top"  
    get "/about" => "public/homes#about", as:"about"
    
    # customer
    devise_for :customers, skip: [:passwords],  controllers: {
      registrations: "public/registrations",
      sessions: "public/sessions"
    }
    
    scope module: :public do
    # namespace :public do
      resource :customers, only: [:show]
      get "/customers/information/edit" => "customers#edit"
      patch "/customers/information" => "customers#update"
      get "/customers/comfirm" => "customers#comfirm"
      patch "/customers/withdrawal" => "customers#withdrawal"
      
      resources :items, only: [:index, :show]
      resources :cart_items, only: [:index, :create, :update, :destroy]
      delete "/cart_items/" => "cart_items#destroy_all"
      
      post "/orders/comfirm" => "orders#comfirm"
      get "/orders/thanks" => "orders#thanks", as:"thanks" #名前をつけることで詳細にリンクするバグを回避
      resources :orders, only: [:index, :new, :create, :show]
      
      resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    end
    
    # admin
    devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
      sessions: "admin/sessions"
    }
    
    namespace :admin do
      resources :genres, only: [:index, :create, :edit, :update]
      resources :items
      resources :customers, only: [:index, :show, :edit, :update] do
      resources :orders, only: [:index]
      end
      resources :orders, only: [:index, :show, :update]
      resources :order_detail, only: [:update]
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
    
    belongs_to :customer
    has_many :order_details, dependent: :destroy
    
    enum payment_method: { credit_card: 0, transfer: 1 }
    enum status: { wating_payment: 0, confirmation_payment: 1, making: 2, preparation: 3, prepared: 4 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def index
    if params[:customer_id]
      @customer = Customer.find(params[:customer_id])
      @orders = @customer.orders.page(params[:page])
      @order_details = OrderDetail.all
      @total_amount = 0
    else
      @orders =Order.page(params[:page])
      @order_details = OrderDetail.all
      @total_amount = 0
    end
  end
  
  def show
    @order = Order.find(params[:id])
    @order_details = OrderDetail.all
    @shopping_cost = 800
    @total_price = 0
  end

  def update
    @order =Order.find(params[:id])
    @order_details = @order.order_details

    if @order.update(order_params)
      @order_details.update_all(making_status: 1) if @order.status == "confirmation_payment"
    end
    redirect_to admin_order_path
  end
  
  private
  
  def order_params
    params.require(:order).permit(:customer_id, :name, :postal_code, :address, :payment_method, :shopping_cost, :total_payment, :status)
  end
  

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      <h4 class="d-inline-block px-3 mt-5 mb-3" style="background-color:#eeeeee">注文履歴一覧</h4>
        <table class="table">
          <thead class="thead-light">
            <th width="30%">購入日時</th>
            <th width="20%">購入者</th>
            <th width="20%">注文個数</th>
            <th width="30%">注文ステータス</th>
          </thead>
          <tbody>
            <% @orders.each do |order| %>
              <tr>
                <td>
                  <%= link_to admin_order_path(order.id) do %>
                    <%= order.created_at.strftime('%Y/%m/%d %H:%M') %></td>
                  <% end %>
                <td><%= order.customer.full_name %></td>
                <td>
                  <% order.order_details.each do |order_detail| %>
                  <% @total_amount += order_detail.amount %>
                  <% end%>
                  <%= @total_amount %>
                </td>
                <td>
                  <%= order.status_i18n %>
                </td>
              </tr>
            <% end %>
          <tbody>
        </table>
    </div>
    <div class="col-3"></div>
  </div>
  <%= paginate @orders, class:"pagination"%>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
    <h4 class="d-inline-block px-3 my-5 ml-5" style="background-color:#eeeeee">注文履歴詳細</h4>
    
  <table class="table table-borderless">
    <tr>
      <td width="10%"><h5 class="font-weight-bold">購入者</h5></td>
      <td><h5>
        <%= link_to admin_customer_orders_path(@order.customer_id) do %>
          <%= @order.customer.full_name %>
        <% end %>
        </h5></td>
    </tr>
    <tr>
      <td width="10%"><h5 class="font-weight-bold">注文日</h5></td>
      <td><h5><%= @order.created_at.strftime('%Y/%m/%d %H:%M') %></h5></td>
    </tr>
    <tr>
      <td width="10%"><h5 class="font-weight-bold">配送先</h5></td>
      <td>
        <h5>
         〒 <%= @order.postal_code.to_s.insert(3, "-") %>　<%= @order.address %></h5><br>
         <h5><%= @order.name %></h5>
      </td>
    </tr>
    <tr>
      <td width="10%"><h5 class="font-weight-bold">支払方法</h5></td>
      <td><h5><%= @order.payment_method_i18n %></h5></td>
    </tr>
    <tr>
      <td width="15%"><h5 class="font-weight-bold">注文ステータス</h5></td>
      <td>
        <h5>
          <%= form_with model: [:admin, @order] do |f| %>
            <!--<%= f.hidden_field :status, :value => @order.status %>-->
            <%= f.hidden_field :customer_id, :value => @order.customer_id %>
            <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]}, {selected: @order.status} %>
            <%= f.submit "更新", class:"btn btn-success px-2 ml-4" %>
          <% end %>
        </h5>
      </td>
    </tr>
  </table>

  <div class="row">
    <div class="col-9 pr-5">
      <table class="table">
        <thead class="thead-light">
          <th width="15%">商品名</th>
          <th width="15%">単価（税込）</th>
          <th width="15%">数量</th>
          <th width="10%">小計</th>
          <th width="10%">製作ステータス</th>
          <th width="3%"></th>
        </thead>
        <tbody>
          
            <% @order.order_details.each do |order_detail|%>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= order_detail.price.to_s(:delimited) %></td>
              <td><%= order_detail.amount %></td>
              <td><%= order_detail.sub_total.to_s(:delimited) %></td>
              <td><h5>
                <%= form_with model: order_detail, url:admin_order_detail_path(order_detail.id), method: :patch do |f| %>
                <%= f.hidden_field :order_id, :value => @order.id %>
                <%= f.hidden_field :item_id, :value => order_detail.item.id %>
                <%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]}, { class:"form-control"} %>
                <td><%= f.submit "更新", class:"btn btn-success px-2" %></td>
              </h5></td>
                <% end %>
                </tr>
            <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-3 pl-5" style="position: relative;">
      <table class="table table-borderless absolute" style="position: absolute; bottom: 0;">
        <tr>
          <th scope="row" width="40%"><h5 class="font-weight-bold">商品合計<h5></th>
          <td align="right">
            <% @order.order_details.each do |order_detail| %>
              <% @total_price += order_detail.sub_total %>
            <% end %>
            <h5><%= @total_price.to_s(:delimited) %>円<h5>
          </td>
        </tr>
        <tr>
          <th scope="row"><h5 class="font-weight-bold">送料<h5></th>
          <td align="right">
            <h5><%= @shopping_cost %>円<h5>
          </td>
        </tr>
        <tr>
          <th scope="row"><h5 class="font-weight-bold">請求額合計<h5></th>
          <td class="font-weight-bold" align="right" width="100%">
            <h5><%= (@total_price + @shopping_cost).to_s(:delimited) %>円<h5>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>