config/routes.rb
Rails.application.routes.draw do

    root to: "public/homes#top"  
    get "/about" => "public/homes#about", as:"about"
    
    # customer
    devise_for :customers, skip: [:passwords],  controllers: {
      registrations: "public/registrations",
      sessions: "public/sessions"
    }
    
    scope module: :public do
    # namespace :public do
      resource :customers, only: [:show]
      get "/customers/information/edit" => "customers#edit"
      patch "/customers/information" => "customers#update"
      get "/customers/comfirm" => "customers#comfirm"
      patch "/customers/withdrawal" => "customers#withdrawal"
      
      resources :items, only: [:index, :show]
      resources :cart_items, only: [:index, :create, :update, :destroy]
      delete "/cart_items/" => "cart_items#destroy_all"
      
      post "/orders/comfirm" => "orders#comfirm"
      get "/orders/thanks" => "orders#thanks", as:"thanks" #名前をつけることで詳細にリンクするバグを回避
      resources :orders, only: [:index, :new, :create, :show]
      
      resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    end
    
    # admin
    devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
      sessions: "admin/sessions"
    }
    
    namespace :admin do
      resources :genres, only: [:index, :create, :edit, :update]
      resources :items
      resources :customers, only: [:index, :show, :edit, :update] do
      resources :orders, only: [:index]
      end
      resources :orders, only: [:index, :show, :update]
      resources :order_detail, only: [:update]
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :customer
  
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :customers, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
  
  def sub_total
    item.add_tax_price * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :Admin
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  validates :first_name, presence:true
  validates :last_name, presence:true
  validates :first_name_kana, presence:true
  validates :last_name_kana, presence:true
  validates :post_code, presence:true
  validates :address, presence:true
  validates :telephone_number, presence:true
  
  # 会員フルネーム
  def full_name
    self.last_name + " " + self.first_name
  end
  
  # 会員カナフルネーム
  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end
  
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details
  
  has_one_attached :item_image

  def add_tax_price
        (self.price * 1.10).round
  end

  def get_item_image(width,height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      item_image.attache(io:File.open(file_path),
      filename: 'default-image.jpg', content_type:'image/jpg')
    end
      item_image.variant(resize_to_limit:[width,height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
    
    belongs_to :customer
    has_many :order_details, dependent: :destroy
    
    enum payment_method: { credit_card: 0, transfer: 1 }
    enum status: { wating_payment: 0, confirmation_payment: 1, making: 2, preparation: 3, prepared: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  belongs_to :order
  belongs_to :item
  
  def sub_total
    item.add_tax_price * amount
  end
  
  enum making_status: { impossible_make: 0, waiting_make: 1, making: 2, complite_make: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end
  
  def index
    @genres = Genre.all 
    @genre = Genre.new
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end
  
  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_path
  end

  def show
    @item = Item.find(params[:id]) 
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, :genre_id, :introduction, :price, :is_active, :item_image)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

# before_action :configure_permitted_parameters, if: :devise_controller?

#   def after_sign_in_path_for(resource)
#     case resource
#       when Admin
#         admin_items_path
#       when Customer
#         root_path
#     end
#   end
  
#   def after_sign_out_path_for(resource_or_scope)
#     if resource_or_scope == :admin
#         root_path
#     elsif resource_or_scope == customers
#         new_admin_session_path
#     else
#         root_path
#     end
#   end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_detail_helper.rb
module Admin::OrderDetailHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/oders_helper.rb
module OdersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="border-bottom">
      <nav class="navbar navbar-expand-xl navbar-light">
        <div class="container">
          <a class="navbar-brand py-3 px-5 btn btn-light" href="/" >LOGO</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>  
          </button>
          <div class="collapse navbar-collapse my-5" id="navbarNavDropdown">
            <% if customer_signed_in? %>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item py-2 px-5">ようこそ、<%= current_customer.last_name %> さん！</li>
              <li class="nav-item"><%= link_to "マイページ", customers_path(current_customer), class: "btn btn-light py-2 px-3 ml-3" %></li>
              <li class="nav-item"><%= link_to "商品一覧", items_path, class: "btn btn-light py-2 px-3 ml-5" %></li>
              <li class="nav-item"><%= link_to "カート", cart_items_path, class: "btn btn-light py-2 px-3 ml-5" %></li>
              <li class="nav-item"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-light py-2 px-3 ml-5" %></li>
            </ul>
            <% elsif admin_signed_in? %>
              <ul class="navbar-nav ml-auto">
              <li class="nav-item"><%= link_to "商品一覧", admin_items_path, class: "btn btn-light py-2 px-3" %></li>
              <li class="nav-item"><%= link_to "会員一覧", admin_customers_path, class: "btn btn-light py-2 px-3 ml-5" %></li>
              <li class="nav-item"><%= link_to "注文履歴一覧", admin_orders_path, class: "btn btn-light py-2 px-3 ml-5" %></li>
              <li class="nav-item"><%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-light py-2 px-3 ml-5" %></li>
              <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-light py-2 px-3 ml-5" %></li>
            </ul>
            <% else %>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item"><%= link_to "About", about_path, class: "btn btn-light py-2 px-3" %></li>
              <li class="nav-item"><%= link_to "商品一覧", about_path, class: "btn btn-light py-2 px-3 ml-5" %></li>
              <li class="nav-item"><%= link_to "新規登録", new_customer_registration_path, class: "btn btn-light py-2 px-3 ml-5" %></li>
              <li class="nav-item"><%= link_to "ログイン", new_customer_session_path, class: "btn btn-light py-2 px-3 ml-5" %></li>
            </ul>
            <% end %>
          </div>
        </div>
      </nav>
    </header>
    
    <%= yield %>
    
    <footer class="border-top py-3 pt-3">
      <p class="text-center">©️nagano-cake</p>
    </footer>
  </body>
</html>